// Generated by gencpp from file eva_driver/eva_joint.msg
// DO NOT EDIT!


#ifndef EVA_DRIVER_MESSAGE_EVA_JOINT_H
#define EVA_DRIVER_MESSAGE_EVA_JOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eva_driver
{
template <class ContainerAllocator>
struct eva_joint_
{
  typedef eva_joint_<ContainerAllocator> Type;

  eva_joint_()
    : j1(0.0)
    , j2(0.0)
    , j3(0.0)
    , j4(0.0)
    , j5(0.0)  {
    }
  eva_joint_(const ContainerAllocator& _alloc)
    : j1(0.0)
    , j2(0.0)
    , j3(0.0)
    , j4(0.0)
    , j5(0.0)  {
  (void)_alloc;
    }



   typedef double _j1_type;
  _j1_type j1;

   typedef double _j2_type;
  _j2_type j2;

   typedef double _j3_type;
  _j3_type j3;

   typedef double _j4_type;
  _j4_type j4;

   typedef double _j5_type;
  _j5_type j5;





  typedef boost::shared_ptr< ::eva_driver::eva_joint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eva_driver::eva_joint_<ContainerAllocator> const> ConstPtr;

}; // struct eva_joint_

typedef ::eva_driver::eva_joint_<std::allocator<void> > eva_joint;

typedef boost::shared_ptr< ::eva_driver::eva_joint > eva_jointPtr;
typedef boost::shared_ptr< ::eva_driver::eva_joint const> eva_jointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eva_driver::eva_joint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eva_driver::eva_joint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eva_driver::eva_joint_<ContainerAllocator1> & lhs, const ::eva_driver::eva_joint_<ContainerAllocator2> & rhs)
{
  return lhs.j1 == rhs.j1 &&
    lhs.j2 == rhs.j2 &&
    lhs.j3 == rhs.j3 &&
    lhs.j4 == rhs.j4 &&
    lhs.j5 == rhs.j5;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eva_driver::eva_joint_<ContainerAllocator1> & lhs, const ::eva_driver::eva_joint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eva_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::eva_driver::eva_joint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eva_driver::eva_joint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eva_driver::eva_joint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eva_driver::eva_joint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eva_driver::eva_joint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eva_driver::eva_joint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eva_driver::eva_joint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7a777ce5080b0b1ffd85e732916f178";
  }

  static const char* value(const ::eva_driver::eva_joint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7a777ce5080b0b1ULL;
  static const uint64_t static_value2 = 0xffd85e732916f178ULL;
};

template<class ContainerAllocator>
struct DataType< ::eva_driver::eva_joint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eva_driver/eva_joint";
  }

  static const char* value(const ::eva_driver::eva_joint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eva_driver::eva_joint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Joint.msg\n"
"\n"
"float64 j1\n"
"float64 j2\n"
"float64 j3\n"
"float64 j4\n"
"float64 j5\n"
;
  }

  static const char* value(const ::eva_driver::eva_joint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eva_driver::eva_joint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.j1);
      stream.next(m.j2);
      stream.next(m.j3);
      stream.next(m.j4);
      stream.next(m.j5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eva_joint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eva_driver::eva_joint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eva_driver::eva_joint_<ContainerAllocator>& v)
  {
    s << indent << "j1: ";
    Printer<double>::stream(s, indent + "  ", v.j1);
    s << indent << "j2: ";
    Printer<double>::stream(s, indent + "  ", v.j2);
    s << indent << "j3: ";
    Printer<double>::stream(s, indent + "  ", v.j3);
    s << indent << "j4: ";
    Printer<double>::stream(s, indent + "  ", v.j4);
    s << indent << "j5: ";
    Printer<double>::stream(s, indent + "  ", v.j5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVA_DRIVER_MESSAGE_EVA_JOINT_H
